# Connects to your ak_admin database
spring.datasource.url=jdbc:mysql://localhost:3306/ak_admin
spring.datasource.username=root
spring.datasource.password=July$157

# Tells Spring Boot to run our table creation script on startup
spring.sql.init.mode=always

# Server Port
server.port=5000